version: "3.8"
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  auth:
    build:
      context: ./auth
      target: builder
    image: auth
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`go4d.test`) && PathPrefix(`/api/auth`)"
    environment:
      - ENV=dev
    volumes:
      - ./auth:/go/src/app
    # have to use $$ (double-dollar) so docker doesn't try to substitute a variable
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"


  client:
    build:
      context: ./client
    image: client
    expose:
      - "3000"
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`go4d.test`) && PathPrefix(`/`)"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on: 
      - reverse-proxy
    # have to use $$ (double-dollar) so docker doesn't try to substitute a variable